all:
	$(MAKE) -C m68ktestapp
	$(MAKE) -C helloworld
	$(MAKE) -C serialbootloader
	$(MAKE) -C serialpayload
	$(MAKE) -C fpgatests

clean:
	$(MAKE) -C m68ktestapp clean
	$(MAKE) -C helloworld clean
	$(MAKE) -C serialbootloader clean
	$(MAKE) -C serialpayload clean
	$(MAKE) -C fpgatests clean
