all:
	$(MAKE) -C m68ktestapp
	$(MAKE) -C helloworld
	$(MAKE) -C serialbootloader
	$(MAKE) -C serialpayload
	$(MAKE) -C fpgatests
	$(MAKE) -C timers
	$(MAKE) -C sound
	$(MAKE) -C input

clean:
	$(MAKE) -C m68ktestapp clean
	$(MAKE) -C helloworld clean
	$(MAKE) -C serialbootloader clean
	$(MAKE) -C serialpayload clean
	$(MAKE) -C fpgatests clean
	$(MAKE) -C timers clean
	$(MAKE) -C sound clean
	$(MAKE) -C input clean
