/*
 * timers_registermasks.h
 *
 *  Created on: 22 Sep 2012
 *      Author: daniel
 */

#ifndef TIMERS_REGISTERMASKS_H_
#define TIMERS_REGISTERMASKS_H_

#define TIMERS_REGISTER_FLAGS_MATCHAINT 1
#define TIMERS_REGISTER_FLAGS_MATHCBINT (1 << 1)

#define TIMERS_REGISTER_CONFIG_ENABLE 1

#define TIMERS_REGISTER_CONFIG_ENMATCHAINT (1 << 1)
#define TIMERS_REGISTER_CONFIG_ENMATCHBINT (1 << 2)

#define TIMERS_REGISTER_CONFIG_RESETMATCHA (1 << 3)
#define TIMERS_REGISTER_CONFIG_RESETMATCHB (1 << 4)

#endif /* TIMERS_REGISTERMASKS_H_ */
