/*
 * soundregistermasks.h
 *
 *  Created on: Jan 1, 2012
 *      Author: daniel
 */

#ifndef SOUNDREGISTERMASKS_H_
#define SOUNDREGISTERMASKS_H_

#define SOUND_CHANNEL_ENABLED 0b1
#define SOUND_CHANNEL_INTERRUPT 0b10
#define SOUND_CHANNEL_LEFT 0b1000
#define SOUND_CHANNEL_RIGHT 0b100
#define SOUND_CHANNEL_RELOAD 0x8000
#define SOUND_CHANNEL_PAGE_SHIFT 9
#define SOUND_CHANNEL_PAGE (0b11 << SOUND_CHANNEL_PAGE_SHIFT)

#endif /* SOUNDREGISTERMASKS_H_ */
