#ifndef VIDEOCARD_H_
#define VIDEOCARD_H_

#define VIDEO_PIXELFORMAT 16
#define VIDEO_PIXELSIZE (VIDEO_PIXELFORMAT/8)

#define VIDEO_WIDTH 480 // physical width
#define VIDEO_HEIGHT 272 // physical height
#define VIDEO_PLAYFIELDWIDTH 512
#define VIDEO_PLAYFIELDHEIGHT 512
#define HBLANKPERIOD 40 //FIXME
#define VBLANKPERIOD 80 //FIXME
#define VIDEO_MEMORYEND (VIDEO_PLAYFIELDWIDTH * VIDEO_PLAYFIELDHEIGHT) * VIDEO_PIXELSIZE
#define VIDEO_REFRESHRATE 50
#define VIDEO_ACTIVEPIXELS (VIDEO_WIDTH * VIDEO_HEIGHT)
#define VIDEO_TOTALPIXELS ((VIDEO_WIDTH + HBLANKPERIOD) * (VIDEO_HEIGHT + VBLANKPERIOD))
#define VIDEO_PIXELSPERSECOND (VIDEO_TOTALPIXELS * VIDEO_REFRESHRATE)

#define VIDEO_REG_FLAGS 0
#define VIDEO_REG_CONFIG 2
#define VIDEO_REG_PIXEL 4
#define VIDEO_REG_LINE 6
#define VIDEO_REG_FRAME 8
#define VIDEO_REG_POSX 10
#define VIDEO_REG_POSY 12
#define VIDEO_REG_WINX 14
#define VIDEO_REG_WINY 16
#define VIDEO_REG_WINWIDTH 18
#define VIDEO_REG_WINHEIGHT 20

#include "card.h"

const card videocard;

void videocard_setosd(SDL_Surface* s);
void videocard_refresh(void);

#endif
